name: Test C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  CMAKE_POLICY_VERSION_MINIMUM: "3.5"

jobs:
  test_cpp:
    name: build (${{ matrix.os }}, ${{ matrix.build-type }})
    
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ matrix.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure
        run: cmake -Stest -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }} -j4

      - name: Test
        run: |
          cd build
          ctest --build-config ${{ matrix.build-type }}
